intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{pypeg}: {h c}{** -version} h{version} $impl_libs $intf_libs

h{version}: in{version} $src_root/manifest

# Build options.
#
c.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: c.poptions += -DLIBPYPEG_STATIC_BUILD
objs{*}: c.poptions += -DLIBPYPEG_SHARED_BUILD

# Export options.
#
lib{pypeg}:
{
  c.export.poptions = "-I$out_root" "-I$src_root"
  c.export.libs = $intf_libs
}

liba{pypeg}: c.export.poptions += -DLIBPYPEG_STATIC
libs{pypeg}: c.export.poptions += -DLIBPYPEG_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{pypeg}: bin.lib.version = "-$version.project_id"
else
  lib{pypeg}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libpypeg/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/libpypeg/
  install.subdirs = true
}
